# These are supported funding model platforms

github: [azeveco]
patreon: Azeveco
ko_fi: azeveco
buy_me_a_coffee: azeveco
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
